# Generated by Django 4.2.2 on 2023-06-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='user',
        ),
    ]
